// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ramrgpgjpyhzcqadxtiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbXJncGdqcHloemNxYWR4dGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0ODIxNDEsImV4cCI6MjA5MDA1ODE0MX0.OADfd0hnuECHzLCHYsOl7U29r4zOBjQau6Zo3fOtcsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});